# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chin Zhi Wei
title: Aspiring Software Engineer
#email: brett.h@email.co.uk
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  chinzhiweiblank
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: zhiwei
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Zhi Wei, an aspiring software engineer.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: CoreDNS Plugin
        link: https://github.com/chinzhiweiblank/coredns-acme
        # link_text: Project Website
        additional_links:
          - title:  CoreDNS
            icon: fab fa-github
            url: github.com/coredns
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Test
        description: | # this will include new lines to allow paragraphs
          Under both the Linux Foundation and Cloud Native Computing Foundation, I made open source contributions to CoreDNS in the form of a plugin that performed the ACME protocol.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Test
        link: test
        sub_title: test
        caption: November 2017 - Present
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
            test
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nanyang Technological University
        caption: 2018-2022
        sub_title: BSc Computer Science, MSc Technology Management
        quote: >
          No idea
        description: | # this will include new lines to allow paragraphs

  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Hoping to really learn frontend once and for all


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
